base_model: meta-llama/Llama-3.2-3B-Instruct

datasets:
  - path: ./data/all_1k_gpt_train.jsonl
    type: chat_template
    train_on_eot: true

val_set_size: 0

test_datasets:
  - path: ./data/all_1k_gpt_val.jsonl
    type: chat_template
    split: train
    train_on_eot: true

output_dir: ./outputs/llama32_3B_lora-32_2e-4_20250720_150739 
chat_template: alpaca

special_tokens:
  pad_token: <|eot_id|>

eval_batch_size: 1
seed: 3

load_in_4bit: true
adapter: lora
lora_r: 32
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj
#batch_size: 16
gradient_accumulation_steps: 4
micro_batch_size: 1
# batch size = micro_batch_size x gradient_accumulation_steps x num_gpus

num_epochs: 10
warmup_ratio: 0.03
learning_rate: 2e-4
lr_scheduler: cosine
gradient_checkpointing: true
early_stopping_patience: 3
save_steps: 10
eval_steps: 10

sequence_len: 3527
optimizer: paged_adamw_8bit    
weight_decay: 0


seed: 1234
